theme: minima

title:  Mark Edzon Araojo
author: Mark Edzon Araojo
description: >
  🇧🇷 Brazilian × 🇵🇭 Filipino.
  Never give up. Keep moving forward.
  Learning, building, and growing one project at a time.
